package com.example.curiosillo.ui.screens.utils

object LegalConstants {
    const val PRIVACY_POLICY_TEXT = """
🛡️ Privacy Policy
Last Updated: April 2026

This Privacy Policy describes how your personal data is collected, used, and shared when you use the mobile application (the "App") managed by Gabriele De Guglielmo (the "Data Controller").

1. Data Controller and Contact Information
Data Controller: Gabriele De Guglielmo

Address: Contrada Tufarole 41, Atripalda (AV)

Email: deguglielmo.gabriele@gmail.com

2. Types of Data Collected
We collect and process the following types of information:

Registration Data: Email address and password.

Third-Party Auth: If you choose "Login with Google," we receive your name and email address from Google.

Technical Data: IP address, device ID, and usage statistics collected via Google Firebase.

Camera Access: The App requires access to your camera to provide specific AI-driven features. Crucially: No photos or videos are saved, stored, or transmitted to our servers. The camera feed is processed in real-time and discarded immediately.

3. Legal Basis for Processing
We process your data based on:

Contractual Necessity: To provide the App’s services and manage your account.

Legitimate Interest: To improve App performance and security via Firebase analytics.

Consent: For specific features where you explicitly grant permission (e.g., Camera access).

4. Age Requirements
The App is not intended for children under the age of 14. By using the App, you declare that you are at least 14 years old. We do not knowingly collect data from individuals below this age without parental consent.

5. Data Retention and Third-Party Services
We use Google Firebase for analytics and authentication. Data is stored on secure servers (typically within the EU). Your account data is kept as long as your account remains active. You may request deletion at any time.

6. Your Rights (GDPR)
You have the right to access, rectify, or delete your personal data, as well as the right to data portability and restriction of processing. To exercise these rights, contact us at the email provided above.
    """

    const val TERMS_OF_SERVICE_TEXT = """
⚖️ Terms of Service (ToS)
Last Updated: April 2026

By downloading or using the App, these terms will automatically apply to you. Please read them carefully.

1. License and AI-Generated Content
The App provides content (text, images, code) generated by Artificial Intelligence (AI).

Disclaimer: AI-generated content is provided "as is." We do not guarantee the accuracy, completeness, or reliability of any content produced by the AI. You use such content at your own risk.

Intellectual Property: All software, design, and original algorithms remain the exclusive property of Gabriele De Guglielmo.

2. User Conduct and Moderation
To maintain a safe environment, users must not use offensive usernames or post offensive comments.

The Three-Strike Rule: If an account is flagged three times for bypassing filters or posting prohibited content, the account will be permanently banned.

Username Policy: We reserve the right to ban accounts with usernames deemed offensive or inappropriate without prior notice.

3. Subscription and Payments (Future Implementation)
The App may offer "Premium" subscription plans.

Automatic Renewal: Subscriptions renew automatically unless canceled.

Cancellation: You can cancel at any time. However, the service will remain active until the end of the current billing cycle. No pro-rata refunds are provided for the remaining period.

4. Limitation of Liability
To the maximum extent permitted by Italian law, the Data Controller shall not be liable for any indirect, incidental, or consequential damages resulting from the use of the App or the inability to use the App, including errors generated by AI models.

5. Termination
We reserve the right to terminate or suspend your access to the App immediately, without prior notice, for conduct that we believe violates these Terms.

6. Governing Law
These Terms are governed by and construed in accordance with the laws of Italy. Any disputes shall be subject to the exclusive jurisdiction of the Italian courts.
    """
}
